united-build: 
language: generic
sudo: required
services:
- docker
before_install:
  - sudo apt-get update
  - echo 'DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -s devicemapper"' | sudo tee /etc/default/docker > /dev/null
  - sudo service docker restart
  - sleep 5
  - sudo docker pull davidva/unibuild-26
script:
- docker run -v $(pwd):/root/enjoy --cap-add=SYS_ADMIN davidva/unibuild-26 /bin/sh -c "rm -f urpms && wget -c https://raw.githubusercontent.com/UnitedRPMS-devel/health-repository/master/test-repo-packages && chmod a+x test-repo-packages && ./test-repo-packages"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8bbc656ea277114ba4fd
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
